### ISSUE TITLE
Errors after #24

### ISSUE THREAD

**Issue by richarddavenport** [caddyserver/replace-response#25]
I restarted caddy with the recent changes and now this is the error I'm getting.

```
{"level":"info","ts":1703113414.5186145,"msg":"using provided configuration","config_file":"/config/caddy.local.json","config_adapter":""}
{"level":"info","ts":1703113414.5215893,"logger":"admin","msg":"admin endpoint started","address":"0.0.0.0:2019","enforce_origin":false,"origins":["//0.0.0.0:2019"]}
{"level":"warn","ts":1703113414.521603,"logger":"admin","msg":"admin endpoint on open interface; host checking disabled","address":"0.0.0.0:2019"}
{"level":"info","ts":1703113414.522009,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"server0","https_port":443}
{"level":"info","ts":1703113414.5220327,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"server0"}
{"level":"info","ts":1703113414.5221372,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x400041aa80"}
panic: interface conversion: interface {} is nil, not *caddy.Replacer

goroutine 1 [running]:
github.com/caddyserver/replace-response.(*Handler).Provision(0x400076b6e0, {{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40003577c0, 0x3, ...}})
        github.com/caddyserver/replace-response@v0.0.0-20231220222707-2b3861c0c7c9/handler.go:88 +0x2f8
github.com/caddyserver/caddy/v2.Context.LoadModuleByID({{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40003577c0, 0x3, 0x4}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/context.go:347 +0x41c
github.com/caddyserver/caddy/v2.Context.loadModuleInline({{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40001643a0, 0x2, 0x2}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/context.go:397 +0x100
github.com/caddyserver/caddy/v2.Context.LoadModule({{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40001643a0, 0x2, 0x2}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/context.go:176 +0x5c0
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Route).ProvisionHandlers(0x40007721b0, {{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40001643a0, 0x2, ...}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/modules/caddyhttp/routes.go:154 +0x98
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.ProvisionHandlers({0x4000772000, 0x4, 0x0?}, {{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, ...}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/modules/caddyhttp/routes.go:209 +0xb8
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Provision({0x4000772000, 0x4, 0x4}, {{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, ...})
        github.com/caddyserver/caddy/v2@v2.7.6/modules/caddyhttp/routes.go:186 +0xb4
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).Provision(0x4000164360, {{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40001643a0, 0x2, ...}})
        github.com/caddyserver/caddy/v2@v2.7.6/modules/caddyhttp/subroute.go:58 +0x90
github.com/caddyserver/caddy/v2.Context.LoadModuleByID({{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40001643a0, 0x2, 0x2}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/context.go:347 +0x41c
github.com/caddyserver/caddy/v2.Context.loadModuleInline({{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40004b28b0, 0x1, 0x1}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/context.go:397 +0x100
github.com/caddyserver/caddy/v2.Context.LoadModule({{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40004b28b0, 0x1, 0x1}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/context.go:176 +0x5c0
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Route).ProvisionHandlers(0x400037bb70, {{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40004b28b0, 0x1, ...}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/modules/caddyhttp/routes.go:154 +0x98
github.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.ProvisionHandlers({0x400037b300, 0x19, 0x4?}, {{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, ...}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/modules/caddyhttp/routes.go:209 +0xb8
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*App).Provision(0x40006f8000, {{0x1a0f8e0, 0x40002df7d0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40004b28b0, 0x1, ...}})
        github.com/caddyserver/caddy/v2@v2.7.6/modules/caddyhttp/app.go:287 +0xa3c
github.com/caddyserver/caddy/v2.Context.LoadModuleByID({{0x1a0f918, 0x40005d20a0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x40004b28b0, 0x1, 0x1}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/context.go:347 +0x41c
github.com/caddyserver/caddy/v2.Context.App({{0x1a0f918, 0x40005d20a0}, 0x4000220de0, 0x40005d2000, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}}, ...)
        github.com/caddyserver/caddy/v2@v2.7.6/context.go:423 +0xf4
github.com/caddyserver/caddy/v2.run.func3(...)
        github.com/caddyserver/caddy/v2@v2.7.6/caddy.go:480
github.com/caddyserver/caddy/v2.run(0x40006b4000?, 0x1)
        github.com/caddyserver/caddy/v2@v2.7.6/caddy.go:485 +0x468
github.com/caddyserver/caddy/v2.unsyncedDecodeAndRun({0x4000466500, 0x2496, 0x2500}, 0x1)
        github.com/caddyserver/caddy/v2@v2.7.6/caddy.go:338 +0xe4
github.com/caddyserver/caddy/v2.changeConfig({0x1519a34, 0x4}, {0x1520983, 0x7}, {0x4000664000, 0x7058, 0x7059}, {0x0, 0x0}, 0x1)
        github.com/caddyserver/caddy/v2@v2.7.6/caddy.go:229 +0x628
github.com/caddyserver/caddy/v2.Load({0x4000664000, 0x7058, 0x7059}, 0x0?)
        github.com/caddyserver/caddy/v2@v2.7.6/caddy.go:128 +0x198
github.com/caddyserver/caddy/v2/cmd.cmdRun({0x0?})
        github.com/caddyserver/caddy/v2@v2.7.6/cmd/commandfuncs.go:231 +0x668
github.com/caddyserver/caddy/v2/cmd.init.1.func2.WrapCommandFuncForCobra.func1(0x4000432600, {0x1519a94?, 0x4?, 0x1519a64?})
        github.com/caddyserver/caddy/v2@v2.7.6/cmd/cobra.go:137 +0x34
github.com/spf13/cobra.(*Command).execute(0x4000432600, {0x400040e680, 0x2, 0x2})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x26a1f00)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/caddyserver/caddy/v2/cmd.Main()
        github.com/caddyserver/caddy/v2@v2.7.6/cmd/main.go:66 +0x68
main.main()
        caddy/main.go:14 +0x1c
```

**Comment by mholt** [comment]
Oh, duh, this is in Provision(), not ServeHTTP(). One sec.

**Comment by francislavoie** [comment]
Sorry, my bad :sweat_smile:

**Comment by mholt** [comment]
Ha no worries, it's ultimately on me for not checking :grin:
